- name: Make sure that Docker config directory exists
  become: yes
  file:
    path: "~/.docker"
    state: "directory"

- name: Ensure Docker client proxy settings are present on the server
  become: yes
  copy:
    content: "{{ docker_proxy_settings }}"
    dest: ~/.docker/config.json

- name: Configure compose
  become: yes
  template:
   src: "../template/docker-compose.yaml.j2"
   dest: "/home/ubuntu/COMP90024/Web/docker-compose.yaml"
   owner: "ubuntu"
   group: "ubuntu"

- name: Run docker compose
  become: yes
  docker_compose:
    project_src: "/home/ubuntu/COMP90024/Web"
    pull: false
    build: yes
    state: present
    remove_orphans: yes
    recreate: always